cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIATU6Z27WSCQ4VKW6R
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/251175566756/my-fifo-queue.fifo
